name: Itential Asset Promotion Pipeline

on:
  workflow_run:
    workflows: ["Integration Promotion Pipeline"]
    types: [completed]

jobs:
  deploy-staging:
    if: github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, '-rc')
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install git+https://github.com/nathaniel-itential/asyncplatform.git@devel

      - name: Find changed files
        id: find-files
        run: bash .github/scripts/assets_diff.sh --stg

      - name: Deploy assets to Staging
        if: steps.find-files.outputs.has_changes == 'true'
        env:
          HOST: ${{ secrets.PLATFORM_HOST }}
          CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
          PROJECT_MEMBERS: ${{ vars.PROJECT_MEMBERS }}
          CHANGED_FILES: ${{ steps.find-files.outputs.changed_files }}
        run: |
          python .github/scripts/deploy.py Staging


  deploy-production:
    if: github.event.workflow_run.conclusion == 'success' && !contains(github.event.workflow_run.head_branch, '-rc')
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install git+https://github.com/nathaniel-itential/asyncplatform.git@devel

      - name: Find changed files
        id: find-files
        run: bash .github/scripts/assets_diff.sh --prod

      - name: Deploy assets to Production
        if: steps.find-files.outputs.has_changes == 'true'
        env:
          HOST: ${{ secrets.PLATFORM_HOST }}
          CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
          PROJECT_MEMBERS: ${{ vars.PROJECT_MEMBERS }}
          CHANGED_FILES: ${{ steps.find-files.outputs.changed_files }}
        run: |
          python .github/scripts/deploy.py Production
