name: Integration Promotion Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  deploy-integrations-staging:
    if: contains(github.ref, '-rc')
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install git+https://github.com/nathaniel-itential/asyncplatform.git@devel

      - name: Find changed specs
        id: find-specs
        run: bash .github/scripts/integration_diff.sh --stg

      - name: Import integration models
        if: steps.find-specs.outputs.has_changes == 'true'
        env:
          HOST: ${{ secrets.PLATFORM_HOST }}
          CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
        run: python .github/scripts/deploy_integrations.py Staging


  deploy-integrations-production:
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install git+https://github.com/nathaniel-itential/asyncplatform.git@devel

      - name: Find changed specs
        id: find-specs
        run: bash .github/scripts/integration_diff.sh --prod

      - name: Import integration models
        if: steps.find-specs.outputs.has_changes == 'true'
        env:
          HOST: ${{ secrets.PLATFORM_HOST }}
          CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
        run: python .github/scripts/deploy_integrations.py Production
